name: Page Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
#     - name: Hugo setup action
#       uses: peaceiris/actions-hugo@v2.2.2
#     - name: Hugo build action
#       run: hugo
    - name: Deploy the site
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.57.2
        TARGET_REPO: benmatselby/benmatselby.github.io
        TOKEN: ${{ secrets.TOKEN }}
